version: '2'
services:
  minion:
    image: opennms/minion:stable
    env_file:
      - .minion.env
    volumes:
        - /opt/minion/etc
        - /opt/minion/data
    command: ["-f"]
    ports:
      - "8201:8201"
      - "18980:18980"
      - "162:162/udp"
      - "514:514/udp"
